# These are supported funding model platforms

github: [your-username]
patreon: languageconnect
open_collective: languageconnect
ko_fi: languageconnect
tidelift: npm/languageconnect
custom: https://languageconnect.com/donate
