[build]
  # Build command
  command = "pnpm build"
  
  # Directory to publish
  publish = ".next"
  
  # Node.js version
  [build.environment]
    NODE_VERSION = "18"
    NPM_FLAGS = "--version"
    PNPM_VERSION = "8"

# Redirects for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Headers for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache"

# Environment variables (you'll need to set these in Netlify dashboard)
[build.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_APP_URL = "https://your-app-name.netlify.app"
