blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/your-username/languageconnect/discussions
    about: Please ask and answer questions here.
  - name: Discord Community
    url: https://discord.gg/languageconnect
    about: Join our Discord community for real-time support.
  - name: Email Support
    url: https://languageconnect.com/contact
    about: Contact us directly via email.
