'use client'

import { createContext, useContext, useEffect, useState, ReactNode } from 'react'
import { AuthUser } from '@/lib/auth'
import { ThemeProvider } from './theme-provider'
import { QueryClient, QueryClientProvider } from 'react-query'
import { SocketProvider } from './socket-provider'

// Auth Context
interface AuthContextType {
  user: AuthUser | null
  loading: boolean
  signIn: (email: string, password: string) => Promise<boolean>
  signUp: (formData: {
    email: string
    password: string
    name: string
    nativeLanguage: string
    learningLanguages: string[]
  }) => Promise<boolean>
  signOut: () => Promise<void>
  signInWithGoogle: () => Promise<boolean>
  signInWithFacebook: () => Promise<boolean>
  resetPassword: (email: string) => Promise<boolean>
}

const AuthContext = createContext<AuthContextType | undefined>(undefined)

export function useAuth() {
  const context = useContext(AuthContext)
  if (context === undefined) {
    throw new Error('useAuth must be used within an AuthProvider')
  }
  return context
}

// Language Context
interface LanguageContextType {
  currentLanguage: string
  setLanguage: (language: string) => void
  isRTL: boolean
  t: (key: string, params?: Record<string, any>) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

// Translations
const translations = {
  he: {
    'app.title': 'LanguageConnect',
    'app.subtitle': 'חיבור בין שפות ותרבויות',
    'auth.login': 'כניסה',
    'auth.register': 'הרשמה',
    'auth.email': 'אימייל',
    'auth.password': 'סיסמה',
    'auth.name': 'שם מלא',
    'auth.forgotPassword': 'שכחתי סיסמה',
    'auth.signInWithGoogle': 'התחבר עם Google',
    'auth.signInWithFacebook': 'התחבר עם Facebook',
    'auth.welcomeTitle': 'ברוכים הבאים ל-LanguageConnect',
    'auth.welcomeDesc': 'המקום המושלם ללימוד שפות וחיבור עם אנשים מכל העולם',
    'auth.features.lessons': 'שיעורים אינטראקטיביים',
    'auth.features.lessonsDesc': 'למד שפות חדשות עם שיעורים מותאמים אישית ומעקב התקדמות',
    'auth.features.connect': 'חיבור גלובלי',
    'auth.features.connectDesc': 'התחבר עם דוברי שפה מקומיים מכל העולם',
    'auth.features.chat': 'צ\'אט ללמידה',
    'auth.features.chatDesc': 'תרגל את השפה שלך בצ\'אט עם תרגום אוטומטי',
    'auth.features.translate': 'תרגום מתקדם',
    'auth.features.translateDesc': 'תרגם טקסטים עם AI מתקדם והבנה תרבותית',
    'translation.clear': 'נקה',
    'translation.translating': 'מתרגם...',
    'translation.translate': 'תרגם',
    'dashboard.welcome': 'ברוכים הבאים',
    'dashboard.welcomeMessage': 'ברוכים הבאים ללוח המחוונים שלכם!',
    'dashboard.home': 'בית',
    'dashboard.lessons': 'שיעורים ותרגולים',
    'dashboard.connect': 'חיבור גלובלי',
    'dashboard.learningChat': 'צ\'אט ללמידה',
    'dashboard.features': 'תכונות מתקדמות',
    'dashboard.forums': 'פורומים ומאמרים',
    'dashboard.profile': 'פרופיל אישי',
    'dashboard.settings': 'הגדרות',
    'dashboard.search': 'חיפוש...',
    'dashboard.stats.totalLessons': 'סה"כ שיעורים',
    'dashboard.stats.completed': 'הושלמו',
    'dashboard.stats.streak': 'רצף ימים',
    'dashboard.stats.achievements': 'הישגים',
    'dashboard.progressOverview': 'סקירת התקדמות',
    'dashboard.overallProgress': 'התקדמות כללית',
    'dashboard.nativeLanguage': 'שפת אם',
    'dashboard.minutesLearned': 'דקות נלמדו',
    'dashboard.quickActions.title': 'פעולות מהירות',
    'dashboard.quickActions.startLesson': 'התחל שיעור',
    'dashboard.quickActions.startLessonDesc': 'התחל שיעור חדש',
    'dashboard.quickActions.findPartners': 'מצא שותפים',
    'dashboard.quickActions.findPartnersDesc': 'מצא שותפים ללמידה',
    'dashboard.quickActions.joinForum': 'הצטרף לפורום',
    'dashboard.quickActions.joinForumDesc': 'הצטרף לדיון בפורום',
    'lessons.title': 'שיעורים ותרגולים',
    'lessons.subtitle': 'למד שפות חדשות עם שיעורים מותאמים אישית',
    'lessons.progress': 'התקדמות',
    'lessons.completed': 'הושלם',
    'lessons.groupWelcome': 'ברוכים הבאים לקבוצת הלמידה!',
    'lessons.groupWelcomeDesc': 'התחילו ללמוד עם הקבוצה שלכם',
    'lessons.letterLearning': 'לימוד אותיות',
    'lessons.totalLessons': 'סה"כ שיעורים',
    'lessons.averageProgress': 'התקדמות ממוצעת',
    'lessons.totalMinutes': 'דקות כולל',
    'lessons.searchPlaceholder': 'חפש שיעורים...',
    'lessons.review': 'סקירה',
    'lessons.continue': 'המשך',
    'lessons.start': 'התחל',
    'lessons.noLessonsFound': 'לא נמצאו שיעורים',
    'lessons.tryDifferentFilters': 'נסה מסננים אחרים',
    'lessons.clearFilters': 'נקה מסננים',
    'globalConnect.title': 'Global Connect',
    'globalConnect.findUsers': 'מצא משתמשים',
    'forums.title': 'פורומים ומאמרים',
    'forums.subtitle': 'שתף רעיונות ולמד עם קהילה גלובלית',
    'forums.categories': 'קטגוריות',
    'forums.stats.activeUsers': 'משתמשים פעילים',
    'forums.searchPosts': 'חפש פוסטים...',
    'forums.moreFilters': 'עוד מסננים',
    'forums.noPostsFound': 'לא נמצאו פוסטים',
    'forums.tryDifferentFilters': 'נסה מסננים אחרים',
    'forums.createPost': 'צור פוסט חדש',
    'forums.allCategories': 'כל הקטגוריות',
    'forums.general': 'כללי',
    'forums.learning': 'למידה',
    'forums.questions': 'שאלות',
    'forums.tips': 'טיפים',
    'forums.offTopic': 'לא קשור',
    'forums.stats.totalPosts': 'סה"כ פוסטים',
    'forums.stats.totalReplies': 'סה"כ תגובות',
    'forums.stats.totalViews': 'סה"כ צפיות',
    'forums.selectCategory': 'בחר קטגוריה',
    'forums.selectLanguage': 'בחר שפה',
    'profile.title': 'פרופיל אישי',
    'profile.settings': 'הגדרות',
    'profile.statistics': 'סטטיסטיקות',
    'settings.title': 'הגדרות',
    'settings.language': 'שפה',
    'settings.theme': 'ערכת נושא',
    'settings.notifications': 'התראות',
    'common.loading': 'טוען...',
    'common.error': 'שגיאה',
    'common.success': 'הצלחה',
    'common.save': 'שמור',
    'common.cancel': 'ביטול',
    'common.delete': 'מחק',
    'common.edit': 'ערוך',
    'common.close': 'סגור',
    'auth.loginSuccess': 'התחברת בהצלחה!',
    'auth.loginError': 'שגיאה בהתחברות',
    'auth.registerSuccess': 'נרשמת בהצלחה!',
    'auth.registerError': 'שגיאה בהרשמה',
    'auth.emailRequired': 'אימייל נדרש',
    'auth.emailInvalid': 'אימייל לא תקין',
    'auth.emailPlaceholder': 'הכנס את האימייל שלך',
    'auth.passwordRequired': 'סיסמה נדרשת',
    'auth.passwordMinLength': 'סיסמה חייבת להכיל לפחות 6 תווים',
    'auth.passwordPlaceholder': 'הכנס את הסיסמה שלך',
    'auth.nameRequired': 'שם נדרש',
    'auth.nameMinLength': 'שם חייב להכיל לפחות 2 תווים',
    'auth.namePlaceholder': 'הכנס את השם המלא שלך',
    'auth.nativeLanguageRequired': 'שפת אם נדרשת',
    'auth.nativeLanguage': 'שפת אם',
    'auth.selectNativeLanguage': 'בחר שפת אם',
    'auth.learningLanguages': 'שפות ללמידה',
    'auth.selectAtLeastOneLanguage': 'בחר לפחות שפה אחת',
    'auth.passwordHelper': 'לפחות 8 תווים, אות גדולה, אות קטנה ומספר',
    'auth.passwordPattern': 'סיסמה חייבת להכיל אות גדולה, אות קטנה ומספר',
    'auth.confirmPasswordRequired': 'אישור סיסמה נדרש',
    'auth.confirmPassword': 'אישור סיסמה',
    'auth.confirmPasswordPlaceholder': 'הכנס שוב את הסיסמה',
    'auth.passwordsDoNotMatch': 'הסיסמאות לא תואמות',
    'auth.orContinueWith': 'או המשך עם',
    'auth.noAccount': 'אין לך חשבון?',
    'auth.haveAccount': 'יש לך כבר חשבון?',
    'auth.resetEmailSent': 'נשלח אימייל לאיפוס סיסמה',
    'auth.resetError': 'שגיאה בשליחת אימייל איפוס',
    'auth.checkYourEmail': 'בדוק את האימייל שלך',
    'auth.resetEmailInstructions': 'שלחנו לך הוראות לאיפוס הסיסמה',
    'auth.sendAnotherEmail': 'שלח אימייל נוסף',
    'auth.backToLogin': 'חזור להתחברות',
    'auth.forgotPasswordInstructions': 'הכנס את האימייל שלך ונשלח לך הוראות לאיפוס הסיסמה',
    'auth.sendResetEmail': 'שלח אימייל איפוס',
    'letters.title': 'לימוד אותיות',
    'letters.teacher': 'מורה מדברת',
    'letters.alphabet': 'אלפבית',
    'letters.pronunciation': 'הגייה',
    'letters.practice': 'תרגול',
    'letters.listen': 'האזן',
    'letters.repeat': 'חזור',
    'letters.next': 'הבא',
    'letters.previous': 'הקודם',
    'letters.complete': 'הושלם',
    'letters.correct': 'נכון!',
    'letters.incorrect': 'לא נכון',
    'letters.tryAgain': 'נסה שוב',
    'letters.wellDone': 'כל הכבוד!',
    'letters.letterSound': 'צליל האות',
    'letters.letterName': 'שם האות',
    'letters.letterForm': 'צורת האות',
    'letters.words': 'מילים',
    'letters.examples': 'דוגמאות',
    'letters.progress': 'התקדמות',
    'letters.level': 'רמה',
    'letters.score': 'ציון',
    'letters.streak': 'רצף',
    'letters.achievements': 'הישגים',
    'letters.startLesson': 'התחל שיעור',
    'letters.continueLesson': 'המשך שיעור',
    'letters.reviewLetters': 'סקור אותיות',
    'letters.quiz': 'חידון',
    'letters.game': 'משחק',
    'letters.story': 'סיפור',
    'letters.song': 'שיר',
    'letters.animation': 'אנימציה',
    'letters.interactive': 'אינטראקטיבי',
    'letters.visual': 'ויזואלי',
    'letters.audio': 'שמע',
    'letters.kinesthetic': 'קינסתטי',
    'letters.difficulty': 'קושי',
    'letters.easy': 'קל',
    'letters.medium': 'בינוני',
    'letters.hard': 'קשה',
    'letters.expert': 'מומחה',
    'letters.speed': 'מהירות',
    'letters.slow': 'איטי',
    'letters.normal': 'רגיל',
    'letters.fast': 'מהיר',
    'letters.voice': 'קול',
    'letters.male': 'זכר',
    'letters.female': 'נקבה',
    'letters.child': 'ילד',
    'letters.adult': 'מבוגר',
    'letters.native': 'דובר יליד',
    'letters.accent': 'מבטא',
    'letters.region': 'אזור',
    'letters.israel': 'ישראל',
    'letters.arabic': 'ערבית',
    'letters.english': 'אנגלית',
    'letters.spanish': 'ספרדית',
    'letters.french': 'צרפתית',
    'letters.german': 'גרמנית',
    'letters.italian': 'איטלקית',
    'letters.portuguese': 'פורטוגזית',
    'letters.russian': 'רוסית',
    'letters.chinese': 'סינית',
    'letters.japanese': 'יפנית',
    'letters.korean': 'קוריאנית',
    'letters.hindi': 'הינדי',
    'letters.sinhala': 'סינהלה',
    'letters.tamil': 'טאמיל',
    'letters.muted': 'מושתק',
    'letters.unmuted': 'לא מושתק',
    'letters.mastered': 'שולט',
    'letters.culturalNotes': 'הערות תרבותיות',
    'letters.congratulations': 'מזל טוב',
    'letters.gameCompleted': 'המשחק הושלם',
    'letters.playAgain': 'שחק שוב',
    'letters.howToPlay': 'איך לשחק',
    'letters.memoryInstructions1': 'לחץ על כרטיסים כדי לגלות אותיות ומילים',
    'letters.memoryInstructions2': 'נסה לזכור את המיקום של כל כרטיס',
    'letters.memoryInstructions3': 'מצא זוגות זהים כדי להשלים את המשחק',
    'letters.memoryInstructions4': 'נסה להשלים במספר מהלכים מינימלי',
    'letters.wordsCompleted': 'מילים הושלמו',
    'letters.hintsUsed': 'רמזים בשימוש',
    'letters.hint': 'רמז',
    'letters.clues': 'רמזים',
    'letters.letters': 'אותיות',
    'letters.submit': 'שלח',
    'letters.crosswordCompleted': 'התשבץ הושלם',
    'letters.crosswordInstructions1': 'לחץ על תא כדי לבחור אותו',
    'letters.crosswordInstructions2': 'הקלד אות כדי למלא את התא',
    'letters.crosswordInstructions3': 'השתמש ברמזים כדי למצוא את המילים הנכונות',
    'letters.crosswordInstructions4': 'השלם את כל המילים כדי לסיים',
    'letters.question': 'שאלה',
    'letters.correctAnswer': 'תשובה נכונה',
    'letters.quizCompleted': 'החידון הושלם',
    'letters.finalScore': 'ציון סופי',
    'letters.quizInstructions1': 'קרא את השאלה בעיון',
    'letters.quizInstructions2': 'בחר את התשובה הנכונה',
    'letters.quizInstructions3': 'לחץ על שלח כדי לאשר את התשובה',
    'letters.quizInstructions4': 'נסה לענות נכון על כל השאלות',
    'letters.practiceLetter': 'תרגל אות',
    'letters.writeLetter': 'כתוב אות',
    'letters.letter': 'אות',
    'letters.attempts': 'ניסיונות',
    'letters.practiceCompleted': 'התרגול הושלם',
    'letters.lettersCompleted': 'אותיות הושלמו',
    'letters.averageAccuracy': 'דיוק ממוצע',
    'letters.practiceAgain': 'תרגל שוב',
    'letters.practiceInstructions1': 'הסתכל על האות המוצגת',
    'letters.practiceInstructions2': 'האזן להגייה שלה',
    'letters.practiceInstructions3': 'כתוב את האות בשדה הטקסט',
    'letters.practiceInstructions4': 'לחץ על שלח כדי לבדוק את התשובה',
    'letters.showStrokeOrder': 'הצג סדר כתיבה',
    'letters.hideStrokeOrder': 'הסתר סדר כתיבה',
    'letters.strokeOrder': 'סדר כתיבה',
    'letters.enterLetter': 'הקלד אות',
    'accessibility.title': 'הגדרות נגישות',
    'accessibility.visualSettings': 'הגדרות חזותיות',
    'accessibility.highContrast': 'ניגודיות גבוהה',
    'accessibility.largeText': 'טקסט גדול',
    'accessibility.reducedMotion': 'הפחתת תנועה',
    'accessibility.keyboardNavigation': 'ניווט מקלדת',
    'accessibility.fontSize': 'גודל גופן',
    'accessibility.cursorSize': 'גודל עכבר',
    'accessibility.soundSettings': 'הגדרות קול',
    'accessibility.soundEffects': 'אפקטי קול',
    'accessibility.screenReader': 'קורא מסך',
    'accessibility.keyboardShortcuts': 'קיצורי מקלדת',
    'accessibility.reset': 'איפוס הגדרות',
    'accessibility.close': 'סגור',
    'accessibility.small': 'קטן',
    'accessibility.normal': 'רגיל',
    'accessibility.large': 'גדול',
    'accessibility.enabled': 'מופעל',
    'accessibility.disabled': 'כבוי',
    'chat.crossLanguageTitle': 'צ\'אט רב-לשוני',
    'chat.crossLanguageDesc': 'תקשורת בין שפות שונות עם תרגום אוטומטי',
    'chat.currentUser': 'משתמש נוכחי',
    'chat.targetUser': 'משתמש יעד',
    'chat.autoTranslate': 'תרגום אוטומטי',
    'chat.noMessages': 'אין הודעות',
    'chat.startConversation': 'התחל שיחה',
    'chat.translated': 'מתורגם',
    'chat.speak': 'השמע',
    'chat.copy': 'העתק',
    'chat.writingIn': 'כותב ב',
    'chat.willBeTranslatedTo': 'יתורגם ל',
    'chat.typeMessage': 'הקלד הודעה',
    'globalConnect.advanced': 'מתקדם',
    'globalConnect.intermediate': 'בינוני',
    'globalConnect.beginner': 'מתחיל',
    'globalConnect.connected': 'מחובר',
    'globalConnect.lastSeen': 'נראה לאחרונה',
    'globalConnect.online': 'מחובר',
    'globalConnect.offline': 'לא מחובר',
    'globalConnect.sendMessage': 'שלח הודעה',
    'globalConnect.addFriend': 'הוסף חבר',
    'globalConnect.viewProfile': 'צפה בפרופיל',
    'globalConnect.languages': 'שפות',
    'globalConnect.nativeLanguage': 'שפת אם',
    'globalConnect.learningLanguages': 'שפות ללמידה',
    'globalConnect.level': 'רמה',
    'globalConnect.location': 'מיקום',
    'globalConnect.status': 'סטטוס',
    'globalConnect.availability': 'זמינות',
    'globalConnect.interests': 'תחומי עניין',
    'globalConnect.hobbies': 'תחביבים',
    'globalConnect.goals': 'מטרות',
    'globalConnect.experience': 'ניסיון',
    'globalConnect.teaching': 'הוראה',
    'globalConnect.learning': 'למידה',
    'globalConnect.practice': 'תרגול',
    'globalConnect.conversation': 'שיחה',
    'globalConnect.grammar': 'דקדוק',
    'globalConnect.vocabulary': 'אוצר מילים',
    'globalConnect.pronunciation': 'הגייה',
    'globalConnect.listening': 'האזנה',
    'globalConnect.speaking': 'דיבור',
    'globalConnect.reading': 'קריאה',
    'globalConnect.writing': 'כתיבה',
    'globalConnect.stats.onlineUsers': 'משתמשים מקוונים',
    'globalConnect.stats.totalUsers': 'סה"כ משתמשים',
    'globalConnect.stats.groups': 'קבוצות',
    'globalConnect.stats.connections': 'חיבורים',
    'globalConnect.searchUsers': 'חפש משתמשים',
    'globalConnect.selectLanguage': 'בחר שפה',
    'globalConnect.selectLevel': 'בחר רמה',
    'globalConnect.selectStatus': 'בחר סטטוס',
    'globalConnect.availableUsers': 'משתמשים פעילים',
    'globalConnect.chat': 'צ\'אט',
    'globalConnect.video': 'וידאו',
    'globalConnect.groups': 'קבוצות',
    'globalConnect.moreFilters': 'סינון נוסף',
    'globalConnect.joinGroup': 'הצטרף לקבוצה',
    'globalConnect.subtitle': 'מצא שותפים ללמידה מכל העולם',
    'globalConnect.videoCall': 'שיחת וידאו',
    'globalConnect.startChat': 'התחל צ\'אט',
    'globalConnect.allLanguages': 'כל השפות',
    'globalConnect.hebrew': 'עברית',
    'globalConnect.arabic': 'ערבית',
    'globalConnect.english': 'אנגלית',
    'globalConnect.sinhala': 'סינהלית',
    'globalConnect.tamil': 'טמילית',
    'globalConnect.allLevels': 'כל הרמות',
    'globalConnect.allStatuses': 'כל הסטטוסים',
    'globalConnect.now': 'עכשיו',
    'globalConnect.minutesAgo': 'לפני {{minutes}} דקות',
    'globalConnect.hoursAgo': 'לפני {{hours}} שעות',
    'globalConnect.daysAgo': 'לפני {{days}} ימים',
    'globalConnect.private': 'פרטי',
    'globalConnect.members': 'חברים',
    'globalConnect.joinGroupSuccess': 'הצטרפת בהצלחה לקבוצה',
    'dashboard.recentAchievements': 'הישגים אחרונים',
    'dashboard.recentLessons': 'שיעורים אחרונים',
    'dashboard.recentActivity': 'פעילות אחרונה',
    'dashboard.todayProgress': 'התקדמות היום',
    'dashboard.weeklyGoal': 'מטרה שבועית',
    'dashboard.monthlyStats': 'סטטיסטיקות חודשיות',
    'dashboard.learningStreak': 'רצף למידה',
    'dashboard.totalTime': 'זמן כולל',
    'dashboard.lessonsCompleted': 'שיעורים הושלמו',
    'dashboard.wordsLearned': 'מילים נלמדו',
    'dashboard.accuracy': 'דיוק',
    'dashboard.speed': 'מהירות',
    'dashboard.consistency': 'עקביות',
    'dashboard.motivation': 'מוטיבציה',
    'dashboard.challenges': 'אתגרים',
    'dashboard.rewards': 'פרסים',
    'dashboard.badges': 'תגים',
    'dashboard.certificates': 'תעודות',
    'dashboard.leaderboard': 'לוח מובילים',
    'dashboard.community': 'קהילה',
    'dashboard.friends': 'חברים',
    'dashboard.mentors': 'מנטורים',
    'dashboard.students': 'תלמידים',
    'dashboard.recommendations': 'המלצות',
    'dashboard.suggestions': 'הצעות',
    'dashboard.tips': 'טיפים',
    'dashboard.tutorials': 'מדריכים',
    'dashboard.help': 'עזרה',
    'dashboard.support': 'תמיכה',
    'dashboard.feedback': 'משוב',
    'dashboard.report': 'דוח',
    'dashboard.analytics': 'אנליטיקה',
    'dashboard.insights': 'תובנות',
    'dashboard.trends': 'מגמות',
    'dashboard.patterns': 'דפוסים',
    'dashboard.goals': 'מטרות',
    'dashboard.objectives': 'יעדים',
    'dashboard.milestones': 'אבני דרך',
    'dashboard.checkpoints': 'נקודות בדיקה',
    'dashboard.assessments': 'הערכות',
    'dashboard.tests': 'מבחנים',
    'dashboard.quizzes': 'חידונים',
    'dashboard.exercises': 'תרגילים',
    'dashboard.practices': 'תרגולים',
    'dashboard.sessions': 'מפגשים',
    'dashboard.courses': 'קורסים',
    'dashboard.modules': 'מודולים',
    'dashboard.units': 'יחידות',
    'dashboard.chapters': 'פרקים',
    'dashboard.topics': 'נושאים',
    'dashboard.subjects': 'מקצועות',
    'dashboard.categories': 'קטגוריות',
    'dashboard.tags': 'תגיות',
    'dashboard.labels': 'תוויות',
    'dashboard.filters': 'מסננים',
    'dashboard.sort': 'מיון',
    'dashboard.browse': 'עיון',
    'dashboard.explore': 'גילוי',
   
    'dashboard.find': 'מציאה',
    'dashboard.locate': 'מיקום',
    'dashboard.navigate': 'ניווט',
    'dashboard.guide': 'הדרכה',
    'dashboard.direct': 'הכוונה',
    'dashboard.lead': 'הובלה',
    'dashboard.follow': 'מעקב',
    'dashboard.track': 'מעקב',
    'dashboard.monitor': 'מעקב',
    'dashboard.observe': 'תצפית',
    'dashboard.watch': 'צפייה',
    'dashboard.view': 'צפייה',
    'dashboard.see': 'ראייה',
    'dashboard.look': 'מבט',
    'dashboard.eye': 'עין',
    'dashboard.vision': 'ראייה',
    'dashboard.sight': 'מראה',
    'dashboard.perspective': 'נקודת מבט',
    'dashboard.angle': 'זווית',
    'dashboard.aspect': 'היבט',
    'dashboard.side': 'צד',
    'dashboard.part': 'חלק',
    'dashboard.section': 'סעיף',
    'dashboard.area': 'אזור',
    'dashboard.zone': 'אזור',
    'dashboard.region': 'אזור',
    'dashboard.territory': 'טריטוריה',
    'dashboard.domain': 'תחום',
    'dashboard.field': 'שדה',
    'dashboard.scope': 'היקף',
    'dashboard.range': 'טווח',
    'dashboard.span': 'טווח',
    'dashboard.extent': 'היקף',
    'dashboard.coverage': 'כיסוי',
    'dashboard.reach': 'הישג',
    'dashboard.access': 'גישה',
    'dashboard.entry': 'כניסה',
    'dashboard.gateway': 'שער',
    'dashboard.portal': 'פורטל',
    'dashboard.interface': 'ממשק',
    'dashboard.surface': 'משטח',
    'dashboard.layer': 'שכבה',
    'dashboard.level': 'רמה',
    'dashboard.tier': 'רמה',
    'dashboard.grade': 'ציון',
    'dashboard.rank': 'דרגה',
    'dashboard.position': 'מיקום',
    'dashboard.place': 'מקום',
    'dashboard.spot': 'נקודה',
    'dashboard.point': 'נקודה',
    'dashboard.location': 'מיקום',
    'dashboard.coordinates': 'קואורדינטות',
    'dashboard.address': 'כתובת',
    'dashboard.destination': 'יעד',
    'dashboard.target': 'מטרה',
    'dashboard.goal': 'מטרה',
    'dashboard.objective': 'יעד',
    'dashboard.aim': 'מטרה',
    'dashboard.purpose': 'מטרה',
    'dashboard.intent': 'כוונה',
    'dashboard.plan': 'תכנית',
    'dashboard.strategy': 'אסטרטגיה',
    'dashboard.approach': 'גישה',
    'dashboard.method': 'שיטה',
    'dashboard.technique': 'טכניקה',
    'dashboard.tactic': 'טקטיקה',
    'dashboard.process': 'תהליך',
    'dashboard.procedure': 'הליך',
    'dashboard.step': 'שלב',
    'dashboard.phase': 'שלב',
    'dashboard.stage': 'שלב',
    'dashboard.period': 'תקופה',
    'dashboard.interval': 'מרווח',
    'dashboard.duration': 'משך',
    'dashboard.timeframe': 'מסגרת זמן',
    'dashboard.schedule': 'לוח זמנים',
    'dashboard.timeline': 'ציר זמן',
    'dashboard.calendar': 'לוח שנה',
    'dashboard.date': 'תאריך',
    'dashboard.time': 'זמן',
    'dashboard.moment': 'רגע',
    'dashboard.instant': 'רגע',
    'dashboard.second': 'שנייה',
    'dashboard.minute': 'דקה',
    'dashboard.hour': 'שעה',
    'dashboard.day': 'יום',
    'dashboard.week': 'שבוע',
    'dashboard.month': 'חודש',
    'dashboard.year': 'שנה',
    'dashboard.decade': 'עשור',
    'dashboard.century': 'מאה',
    'dashboard.millennium': 'אלף',
    'dashboard.era': 'עידן',
    'dashboard.age': 'גיל',
    'dashboard.generation': 'דור',
    'dashboard.epoch': 'תקופה',
    'dashboard.cycle': 'מחזור',
    'dashboard.rotation': 'סיבוב',
    'dashboard.revolution': 'מהפכה',
    'dashboard.evolution': 'התפתחות',
    'dashboard.development': 'פיתוח',
    'dashboard.growth': 'צמיחה',
    'dashboard.progress': 'התקדמות',
    'dashboard.advancement': 'קידום',
    'dashboard.improvement': 'שיפור',
    'dashboard.enhancement': 'שיפור',
    'dashboard.upgrade': 'שדרוג',
    'dashboard.update': 'עדכון',
    'dashboard.refresh': 'רענון',
    'dashboard.renewal': 'חידוש',
    'dashboard.restoration': 'שיקום',
    'dashboard.recovery': 'התאוששות',
    'dashboard.revival': 'תחייה',
    'dashboard.rebirth': 'לידה מחדש',
    'dashboard.renaissance': 'רנסנס',
  },
  ar: {
    'app.title': 'LanguageConnect',
    'app.subtitle': 'ربط اللغات والثقافات',
    'auth.login': 'تسجيل الدخول',
    'auth.register': 'التسجيل',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.name': 'الاسم الكامل',
    'auth.forgotPassword': 'نسيت كلمة المرور',
    'auth.signInWithGoogle': 'تسجيل الدخول بـ Google',
    'auth.signInWithFacebook': 'تسجيل الدخول بـ Facebook',
    'auth.welcomeTitle': 'مرحباً بك في LanguageConnect',
    'auth.welcomeDesc': 'المكان المثالي لتعلم اللغات والتواصل مع أشخاص من جميع أنحاء العالم',
    'auth.features.lessons': 'دروس تفاعلية',
    'auth.features.lessonsDesc': 'تعلم لغات جديدة مع دروس مخصصة ومتابعة التقدم',
    'auth.features.connect': 'الاتصال العالمي',
    'auth.features.connectDesc': 'تواصل مع متحدثي اللغة الأصليين من جميع أنحاء العالم',
    'auth.features.chat': 'دردشة التعلم',
    'auth.features.chatDesc': 'تدرب على لغتك في دردشة مع ترجمة تلقائية',
    'auth.features.translate': 'ترجمة متقدمة',
    'auth.features.translateDesc': 'ترجم النصوص بـ AI متقدم وفهم ثقافي',
    'translation.clear': 'مسح',
    'translation.translating': 'جاري الترجمة...',
    'translation.translate': 'ترجم',
    'dashboard.welcome': 'مرحباً',
    'dashboard.welcomeMessage': 'مرحباً بك في لوحة التحكم الخاصة بك!',
    'dashboard.home': 'الرئيسية',
    'dashboard.lessons': 'الدروس والتمارين',
    'dashboard.connect': 'الاتصال العالمي',
    'dashboard.learningChat': 'دردشة التعلم',
    'dashboard.features': 'الميزات المتقدمة',
    'dashboard.forums': 'المنتديات والمقالات',
    'dashboard.profile': 'الملف الشخصي',
    'dashboard.settings': 'الإعدادات',
    'dashboard.search': 'البحث...',
    'dashboard.stats.totalLessons': 'إجمالي الدروس',
    'dashboard.stats.completed': 'مكتملة',
    'dashboard.stats.streak': 'أيام متتالية',
    'dashboard.stats.achievements': 'الإنجازات',
    'dashboard.progressOverview': 'نظرة عامة على التقدم',
    'dashboard.overallProgress': 'التقدم العام',
    'dashboard.nativeLanguage': 'اللغة الأم',
    'dashboard.minutesLearned': 'دقائق تعلمت',
    'dashboard.quickActions.title': 'إجراءات سريعة',
    'dashboard.quickActions.startLesson': 'ابدأ الدرس',
    'dashboard.quickActions.startLessonDesc': 'ابدأ درساً جديداً',
    'dashboard.quickActions.findPartners': 'ابحث عن شركاء',
    'dashboard.quickActions.findPartnersDesc': 'ابحث عن شركاء للتعلم',
    'dashboard.quickActions.joinForum': 'انضم للمنتدى',
    'dashboard.quickActions.joinForumDesc': 'انضم للنقاش في المنتدى',
    'letters.muted': 'مكتوم',
    'letters.unmuted': 'غير مكتوم',
    'letters.mastered': 'متقن',
    'letters.culturalNotes': 'ملاحظات ثقافية',
    'chat.crossLanguageTitle': 'دردشة متعددة اللغات',
    'chat.crossLanguageDesc': 'التواصل بين لغات مختلفة مع ترجمة تلقائية',
    'chat.currentUser': 'المستخدم الحالي',
    'chat.targetUser': 'المستخدم المستهدف',
    'chat.autoTranslate': 'ترجمة تلقائية',
    'chat.noMessages': 'لا توجد رسائل',
    'chat.startConversation': 'ابدأ المحادثة',
    'chat.translated': 'مترجم',
    'chat.speak': 'تحدث',
    'chat.copy': 'انسخ',
    'chat.writingIn': 'يكتب بـ',
    'chat.willBeTranslatedTo': 'سيترجم إلى',
    'chat.typeMessage': 'اكتب رسالة',
    'globalConnect.advanced': 'متقدم',
    'globalConnect.intermediate': 'متوسط',
    'globalConnect.beginner': 'مبتدئ',
    'globalConnect.connected': 'متصل',
    'globalConnect.lastSeen': 'شوهد آخر مرة',
    'globalConnect.online': 'متصل',
    'globalConnect.offline': 'غير متصل',
    'globalConnect.startChat': 'ابدأ المحادثة',
    'globalConnect.allLanguages': 'جميع اللغات',
    'globalConnect.hebrew': 'العبرية',
    'globalConnect.arabic': 'العربية',
    'globalConnect.english': 'الإنجليزية',
    'globalConnect.sinhala': 'السنهالية',
    'globalConnect.tamil': 'التاميلية',
    'globalConnect.allLevels': 'جميع المستويات',
    'globalConnect.allStatuses': 'جميع الحالات',
    'globalConnect.now': 'الآن',
    'globalConnect.minutesAgo': 'منذ {{minutes}} دقيقة',
    'globalConnect.hoursAgo': 'منذ {{hours}} ساعة',
    'globalConnect.daysAgo': 'منذ {{days}} يوم',
    'globalConnect.private': 'خاص',
    'globalConnect.members': 'أعضاء',
    'globalConnect.joinGroupSuccess': 'انضممت بنجاح إلى المجموعة',
    'globalConnect.sendMessage': 'أرسل رسالة',
    'globalConnect.addFriend': 'أضف صديق',
    'globalConnect.viewProfile': 'عرض الملف الشخصي',
    'globalConnect.languages': 'اللغات',
    'globalConnect.nativeLanguage': 'اللغة الأم',
    'globalConnect.learningLanguages': 'اللغات للتعلم',
    'globalConnect.level': 'المستوى',
    'globalConnect.location': 'الموقع',
    'globalConnect.status': 'الحالة',
    'globalConnect.availability': 'التوفر',
    'globalConnect.interests': 'الاهتمامات',
    'globalConnect.hobbies': 'الهوايات',
    'globalConnect.goals': 'الأهداف',
    'globalConnect.experience': 'الخبرة',
    'globalConnect.teaching': 'التدريس',
    'globalConnect.learning': 'التعلم',
    'globalConnect.practice': 'الممارسة',
    'globalConnect.conversation': 'المحادثة',
    'globalConnect.grammar': 'القواعد',
    'globalConnect.vocabulary': 'المفردات',
    'globalConnect.pronunciation': 'النطق',
    'globalConnect.listening': 'الاستماع',
    'globalConnect.speaking': 'التحدث',
    'globalConnect.reading': 'القراءة',
    'globalConnect.writing': 'الكتابة',
    'globalConnect.stats.onlineUsers': 'المستخدمون المتصلون',
    'globalConnect.stats.totalUsers': 'إجمالي المستخدمين',
    'globalConnect.stats.groups': 'المجموعات',
    'globalConnect.stats.connections': 'الاتصالات',
    'globalConnect.searchUsers': 'البحث عن المستخدمين',
    'globalConnect.selectLanguage': 'اختر اللغة',
    'globalConnect.selectLevel': 'اختر المستوى',
    'globalConnect.selectStatus': 'اختر الحالة',
    'globalConnect.availableUsers': 'المستخدمون النشطون',
    'globalConnect.chat': 'الدردشة',
    'globalConnect.video': 'الفيديو',
    'globalConnect.groups': 'المجموعات',
    'globalConnect.moreFilters': 'المزيد من المرشحات',
    'globalConnect.joinGroup': 'انضم إلى المجموعة',
    'globalConnect.subtitle': 'ابحث عن شركاء تعلم من جميع أنحاء العالم',
    'globalConnect.videoCall': 'مكالمة فيديو',
    'dashboard.recentAchievements': 'الإنجازات الأخيرة',
    'dashboard.recentLessons': 'الدروس الأخيرة',
    'dashboard.recentActivity': 'النشاط الأخير',
    'dashboard.todayProgress': 'تقدم اليوم',
    'dashboard.weeklyGoal': 'الهدف الأسبوعي',
    'dashboard.monthlyStats': 'الإحصائيات الشهرية',
    'dashboard.learningStreak': 'سلسلة التعلم',
    'dashboard.totalTime': 'الوقت الإجمالي',
    'dashboard.lessonsCompleted': 'الدروس المكتملة',
    'dashboard.wordsLearned': 'الكلمات المتعلمة',
    'dashboard.accuracy': 'الدقة',
    'dashboard.speed': 'السرعة',
    'dashboard.consistency': 'الاتساق',
    'dashboard.motivation': 'الدافع',
    'dashboard.challenges': 'التحديات',
    'dashboard.rewards': 'المكافآت',
    'dashboard.badges': 'الشارات',
    'dashboard.certificates': 'الشهادات',
    'dashboard.leaderboard': 'لوحة المتصدرين',
    'dashboard.community': 'المجتمع',
    'dashboard.friends': 'الأصدقاء',
    'dashboard.mentors': 'الموجهون',
    'dashboard.students': 'الطلاب',
    'dashboard.recommendations': 'التوصيات',
    'dashboard.suggestions': 'الاقتراحات',
    'dashboard.tips': 'النصائح',
    'dashboard.tutorials': 'البرامج التعليمية',
    'dashboard.help': 'المساعدة',
    'dashboard.support': 'الدعم',
    'dashboard.feedback': 'التعليقات',
    'dashboard.report': 'التقرير',
    'dashboard.analytics': 'التحليلات',
    'dashboard.insights': 'الرؤى',
    'dashboard.trends': 'الاتجاهات',
    'dashboard.patterns': 'الأنماط',
    'dashboard.objectives': 'الأهداف',
    'dashboard.milestones': 'المعالم',
    'dashboard.checkpoints': 'نقاط التحقق',
    'dashboard.assessments': 'التقييمات',
    'dashboard.tests': 'الاختبارات',
    'dashboard.quizzes': 'الاختبارات القصيرة',
    'dashboard.exercises': 'التمارين',
    'dashboard.practices': 'الممارسات',
    'dashboard.sessions': 'الجلسات',
    'dashboard.courses': 'الدورات',
    'dashboard.modules': 'الوحدات',
    'dashboard.units': 'الوحدات',
    'dashboard.chapters': 'الفصول',
    'dashboard.topics': 'المواضيع',
    'dashboard.subjects': 'المواد',
    'dashboard.categories': 'الفئات',
    'dashboard.tags': 'العلامات',
    'dashboard.labels': 'التسميات',
    'dashboard.filters': 'المرشحات',
    'dashboard.sort': 'الترتيب',
    'dashboard.browse': 'التصفح',
    'dashboard.explore': 'الاستكشاف',
    'dashboard.discover': 'الاكتشاف',
    'dashboard.find': 'العثور',
    'dashboard.locate': 'تحديد الموقع',
    'dashboard.navigate': 'التنقل',
    'dashboard.guide': 'الدليل',
    'dashboard.direct': 'التوجيه',
    'dashboard.lead': 'القيادة',
    'dashboard.follow': 'المتابعة',
    'dashboard.track': 'التتبع',
    'dashboard.monitor': 'المراقبة',
    'dashboard.observe': 'المراقبة',
    'dashboard.watch': 'المشاهدة',
    'dashboard.view': 'العرض',
    'dashboard.see': 'الرؤية',
    'dashboard.look': 'النظر',
    'dashboard.eye': 'العين',
    'dashboard.vision': 'الرؤية',
    'dashboard.sight': 'البصر',
    'dashboard.perspective': 'وجهة النظر',
    'dashboard.angle': 'الزاوية',
    'dashboard.aspect': 'الجانب',
    'dashboard.side': 'الجانب',
    'dashboard.part': 'الجزء',
    'dashboard.section': 'القسم',
    'dashboard.area': 'المنطقة',
    'dashboard.zone': 'المنطقة',
    'dashboard.region': 'المنطقة',
    'dashboard.territory': 'الإقليم',
    'dashboard.domain': 'المجال',
    'dashboard.field': 'المجال',
    'dashboard.scope': 'النطاق',
    'dashboard.range': 'النطاق',
    'dashboard.span': 'المدى',
    'dashboard.extent': 'المدى',
    'dashboard.coverage': 'التغطية',
    'dashboard.reach': 'الوصول',
    'dashboard.access': 'الوصول',
    'dashboard.entry': 'الدخول',
    'dashboard.gateway': 'البوابة',
    'dashboard.portal': 'البوابة',
    'dashboard.interface': 'الواجهة',
    'dashboard.surface': 'السطح',
    'dashboard.layer': 'الطبقة',
    'dashboard.level': 'المستوى',
    'dashboard.tier': 'المستوى',
    'dashboard.grade': 'الدرجة',
    'dashboard.rank': 'الرتبة',
    'dashboard.position': 'الموضع',
    'dashboard.place': 'المكان',
    'dashboard.spot': 'النقطة',
    'dashboard.point': 'النقطة',
    'dashboard.location': 'الموقع',
    'dashboard.coordinates': 'الإحداثيات',
    'dashboard.address': 'العنوان',
    'dashboard.destination': 'الوجهة',
    'dashboard.target': 'الهدف',
    'dashboard.goal': 'الهدف',
    'dashboard.objective': 'الهدف',
    'dashboard.aim': 'الهدف',
    'dashboard.purpose': 'الغرض',
    'dashboard.intent': 'النية',
    'dashboard.plan': 'الخطة',
    'dashboard.strategy': 'الاستراتيجية',
    'dashboard.approach': 'النهج',
    'dashboard.method': 'الطريقة',
    'dashboard.technique': 'التقنية',
    'dashboard.tactic': 'التكتيك',
    'dashboard.process': 'العملية',
    'dashboard.procedure': 'الإجراء',
    'dashboard.step': 'الخطوة',
    'dashboard.phase': 'المرحلة',
    'dashboard.stage': 'المرحلة',
    'dashboard.period': 'الفترة',
    'dashboard.interval': 'الفترة',
    'dashboard.duration': 'المدة',
    'dashboard.timeframe': 'الإطار الزمني',
    'dashboard.schedule': 'الجدول',
    'dashboard.timeline': 'الجدول الزمني',
    'dashboard.calendar': 'التقويم',
    'dashboard.date': 'التاريخ',
    'dashboard.time': 'الوقت',
    'dashboard.moment': 'اللحظة',
    'dashboard.instant': 'اللحظة',
    'dashboard.second': 'الثانية',
    'dashboard.minute': 'الدقيقة',
    'dashboard.hour': 'الساعة',
    'dashboard.day': 'اليوم',
    'dashboard.week': 'الأسبوع',
    'dashboard.month': 'الشهر',
    'dashboard.year': 'السنة',
    'dashboard.decade': 'العقد',
    'dashboard.century': 'القرن',
    'dashboard.millennium': 'الألفية',
    'dashboard.era': 'العصر',
    'dashboard.age': 'العمر',
    'dashboard.generation': 'الجيل',
    'dashboard.epoch': 'العصر',
    'dashboard.cycle': 'الدورة',
    'dashboard.rotation': 'الدوران',
    'dashboard.revolution': 'الثورة',
    'dashboard.evolution': 'التطور',
    'dashboard.development': 'التطوير',
    'dashboard.growth': 'النمو',
    'dashboard.progress': 'التقدم',
    'dashboard.advancement': 'التقدم',
    'dashboard.improvement': 'التحسين',
    'dashboard.enhancement': 'التحسين',
    'dashboard.upgrade': 'الترقية',
    'dashboard.update': 'التحديث',
    'dashboard.refresh': 'التحديث',
    'dashboard.renewal': 'التجديد',
    'dashboard.restoration': 'الاستعادة',
    'dashboard.recovery': 'الاسترداد',
    'dashboard.revival': 'الإحياء',
    'dashboard.rebirth': 'الولادة الجديدة',
    'dashboard.renaissance': 'النهضة',
    'lessons.title': 'الدروس والتمارين',
    'lessons.subtitle': 'تعلم لغات جديدة مع دروس مخصصة',
    'lessons.progress': 'التقدم',
    'lessons.completed': 'مكتمل',
    'lessons.groupWelcome': 'مرحباً بكم في مجموعة التعلم!',
    'lessons.groupWelcomeDesc': 'ابدأوا التعلم مع مجموعتكم',
    'lessons.letterLearning': 'تعلم الحروف',
    'lessons.totalLessons': 'إجمالي الدروس',
    'lessons.averageProgress': 'التقدم المتوسط',
    'lessons.totalMinutes': 'دقائق إجمالي',
    'lessons.searchPlaceholder': 'البحث في الدروس...',
    'lessons.review': 'مراجعة',
    'lessons.continue': 'متابعة',
    'lessons.start': 'ابدأ',
    'lessons.noLessonsFound': 'لم يتم العثور على دروس',
    'lessons.tryDifferentFilters': 'جرب مرشحات مختلفة',
    'lessons.clearFilters': 'مسح المرشحات',
    'globalConnect.title': 'Global Connect',
    'globalConnect.findUsers': 'البحث عن المستخدمين',
    'forums.title': 'المنتديات والمقالات',
    'forums.subtitle': 'شارك الأفكار وتعلم مع مجتمع عالمي',
    'forums.categories': 'الفئات',
    'forums.stats.activeUsers': 'المستخدمون النشطون',
    'forums.searchPosts': 'البحث في المنشورات...',
    'forums.moreFilters': 'المزيد من المرشحات',
    'forums.noPostsFound': 'لم يتم العثور على منشورات',
    'forums.tryDifferentFilters': 'جرب مرشحات مختلفة',
    'forums.createPost': 'إنشاء منشور جديد',
    'forums.allCategories': 'جميع الفئات',
    'forums.general': 'عام',
    'forums.learning': 'التعلم',
    'forums.questions': 'الأسئلة',
    'forums.tips': 'النصائح',
    'forums.offTopic': 'خارج الموضوع',
    'forums.stats.totalPosts': 'إجمالي المنشورات',
    'forums.stats.totalReplies': 'إجمالي الردود',
    'forums.stats.totalViews': 'إجمالي المشاهدات',
    'forums.selectCategory': 'اختر الفئة',
    'forums.selectLanguage': 'اختر اللغة',
    'profile.title': 'الملف الشخصي',
    'profile.settings': 'الإعدادات',
    'profile.statistics': 'الإحصائيات',
    'settings.title': 'الإعدادات',
    'settings.language': 'اللغة',
    'settings.theme': 'المظهر',
    'settings.notifications': 'الإشعارات',
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجح',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.close': 'إغلاق',
    'auth.loginSuccess': 'تم تسجيل الدخول بنجاح!',
    'auth.loginError': 'خطأ في تسجيل الدخول',
    'auth.registerSuccess': 'تم التسجيل بنجاح!',
    'auth.registerError': 'خطأ في التسجيل',
    'auth.emailRequired': 'البريد الإلكتروني مطلوب',
    'auth.emailInvalid': 'البريد الإلكتروني غير صحيح',
    'auth.emailPlaceholder': 'أدخل بريدك الإلكتروني',
    'auth.passwordRequired': 'كلمة المرور مطلوبة',
    'auth.passwordMinLength': 'كلمة المرور يجب أن تحتوي على 6 أحرف على الأقل',
    'auth.passwordPlaceholder': 'أدخل كلمة المرور',
    'auth.nameRequired': 'الاسم مطلوب',
    'auth.nameMinLength': 'الاسم يجب أن يحتوي على حرفين على الأقل',
    'auth.namePlaceholder': 'أدخل اسمك الكامل',
    'auth.nativeLanguageRequired': 'اللغة الأم مطلوبة',
    'auth.nativeLanguage': 'اللغة الأم',
    'auth.selectNativeLanguage': 'اختر اللغة الأم',
    'auth.learningLanguages': 'اللغات للتعلم',
    'auth.selectAtLeastOneLanguage': 'اختر لغة واحدة على الأقل',
    'auth.passwordHelper': '8 أحرف على الأقل، حرف كبير، حرف صغير ورقم',
    'auth.passwordPattern': 'كلمة المرور يجب أن تحتوي على حرف كبير، حرف صغير ورقم',
    'auth.confirmPasswordRequired': 'تأكيد كلمة المرور مطلوب',
    'auth.confirmPassword': 'تأكيد كلمة المرور',
    'auth.confirmPasswordPlaceholder': 'أدخل كلمة المرور مرة أخرى',
    'auth.passwordsDoNotMatch': 'كلمات المرور غير متطابقة',
    'auth.orContinueWith': 'أو تابع مع',
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.haveAccount': 'لديك حساب بالفعل؟',
    'auth.resetEmailSent': 'تم إرسال بريد إلكتروني لإعادة تعيين كلمة المرور',
    'auth.resetError': 'خطأ في إرسال بريد إعادة التعيين',
    'auth.checkYourEmail': 'تحقق من بريدك الإلكتروني',
    'auth.resetEmailInstructions': 'أرسلنا لك تعليمات لإعادة تعيين كلمة المرور',
    'auth.sendAnotherEmail': 'إرسال بريد إلكتروني آخر',
    'auth.backToLogin': 'العودة لتسجيل الدخول',
    'auth.forgotPasswordInstructions': 'أدخل بريدك الإلكتروني وسنرسل لك تعليمات لإعادة تعيين كلمة المرور',
    'auth.sendResetEmail': 'إرسال بريد إعادة التعيين',
  },
  en: {
    'app.title': 'LanguageConnect',
    'app.subtitle': 'Connecting Languages and Cultures',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.name': 'Full Name',
    'auth.forgotPassword': 'Forgot Password',
    'auth.signInWithGoogle': 'Sign in with Google',
    'auth.signInWithFacebook': 'Sign in with Facebook',
    'auth.welcomeTitle': 'Welcome to LanguageConnect',
    'auth.welcomeDesc': 'The perfect place to learn languages and connect with people from around the world',
    'auth.features.lessons': 'Interactive Lessons',
    'auth.features.lessonsDesc': 'Learn new languages with personalized lessons and progress tracking',
    'auth.features.connect': 'Global Connect',
    'auth.features.connectDesc': 'Connect with native speakers from around the world',
    'auth.features.chat': 'Learning Chat',
    'auth.features.chatDesc': 'Practice your language skills in chat with automatic translation',
    'auth.features.translate': 'Advanced Translation',
    'auth.features.translateDesc': 'Translate texts with advanced AI and cultural understanding',
    'translation.clear': 'Clear',
    'translation.translating': 'Translating...',
    'translation.translate': 'Translate',
    'dashboard.welcome': 'Welcome',
    'dashboard.welcomeMessage': 'Welcome to your dashboard!',
    'dashboard.home': 'Home',
    'dashboard.lessons': 'Lessons & Practice',
    'dashboard.connect': 'Global Connect',
    'dashboard.learningChat': 'Learning Chat',
    'dashboard.features': 'Advanced Features',
    'dashboard.forums': 'Forums & Articles',
    'dashboard.profile': 'Profile',
    'dashboard.settings': 'Settings',
    'dashboard.search': 'Search...',
    'dashboard.stats.totalLessons': 'Total Lessons',
    'dashboard.stats.completed': 'Completed',
    'dashboard.stats.streak': 'Day Streak',
    'dashboard.stats.achievements': 'Achievements',
    'dashboard.progressOverview': 'Progress Overview',
    'dashboard.overallProgress': 'Overall Progress',
    'dashboard.nativeLanguage': 'Native Language',
    'dashboard.minutesLearned': 'Minutes Learned',
    'dashboard.quickActions.title': 'Quick Actions',
    'dashboard.quickActions.startLesson': 'Start Lesson',
    'dashboard.quickActions.startLessonDesc': 'Start a new lesson',
    'dashboard.quickActions.findPartners': 'Find Partners',
    'dashboard.quickActions.findPartnersDesc': 'Find learning partners',
    'dashboard.quickActions.joinForum': 'Join Forum',
    'dashboard.quickActions.joinForumDesc': 'Join forum discussion',
    'letters.muted': 'Muted',
    'letters.unmuted': 'Unmuted',
    'letters.mastered': 'Mastered',
    'letters.culturalNotes': 'Cultural Notes',
    'chat.crossLanguageTitle': 'Cross-Language Chat',
    'chat.crossLanguageDesc': 'Communication between different languages with automatic translation',
    'chat.currentUser': 'Current User',
    'chat.targetUser': 'Target User',
    'chat.autoTranslate': 'Auto Translate',
    'chat.noMessages': 'No messages',
    'chat.startConversation': 'Start conversation',
    'chat.translated': 'Translated',
    'chat.speak': 'Speak',
    'chat.copy': 'Copy',
    'chat.writingIn': 'Writing in',
    'chat.willBeTranslatedTo': 'Will be translated to',
    'chat.typeMessage': 'Type message',
    'globalConnect.advanced': 'Advanced',
    'globalConnect.intermediate': 'Intermediate',
    'globalConnect.beginner': 'Beginner',
    'globalConnect.connected': 'Connected',
    'globalConnect.lastSeen': 'Last seen',
    'globalConnect.online': 'Online',
    'globalConnect.offline': 'Offline',
    'globalConnect.sendMessage': 'Send Message',
    'globalConnect.addFriend': 'Add Friend',
    'globalConnect.viewProfile': 'View Profile',
    'globalConnect.languages': 'Languages',
    'globalConnect.nativeLanguage': 'Native Language',
    'globalConnect.learningLanguages': 'Learning Languages',
    'globalConnect.level': 'Level',
    'globalConnect.location': 'Location',
    'globalConnect.status': 'Status',
    'globalConnect.availability': 'Availability',
    'globalConnect.interests': 'Interests',
    'globalConnect.hobbies': 'Hobbies',
    'globalConnect.goals': 'Goals',
    'globalConnect.experience': 'Experience',
    'globalConnect.teaching': 'Teaching',
    'globalConnect.learning': 'Learning',
    'globalConnect.practice': 'Practice',
    'globalConnect.conversation': 'Conversation',
    'globalConnect.grammar': 'Grammar',
    'globalConnect.vocabulary': 'Vocabulary',
    'globalConnect.pronunciation': 'Pronunciation',
    'globalConnect.listening': 'Listening',
    'globalConnect.speaking': 'Speaking',
    'globalConnect.reading': 'Reading',
    'globalConnect.writing': 'Writing',
    'globalConnect.stats.onlineUsers': 'Online Users',
    'globalConnect.stats.totalUsers': 'Total Users',
    'globalConnect.stats.groups': 'Groups',
    'globalConnect.stats.connections': 'Connections',
    'globalConnect.searchUsers': 'Search Users',
    'globalConnect.selectLanguage': 'Select Language',
    'globalConnect.selectLevel': 'Select Level',
    'globalConnect.selectStatus': 'Select Status',
    'globalConnect.availableUsers': 'Active Users',
    'globalConnect.chat': 'Chat',
    'globalConnect.video': 'Video',
    'globalConnect.groups': 'Groups',
    'globalConnect.moreFilters': 'More Filters',
    'globalConnect.joinGroup': 'Join Group',
    'globalConnect.subtitle': 'Find learning partners from around the world',
    'globalConnect.videoCall': 'Video Call',
    'globalConnect.startChat': 'Start Chat',
    'globalConnect.allLanguages': 'All Languages',
    'globalConnect.hebrew': 'Hebrew',
    'globalConnect.arabic': 'Arabic',
    'globalConnect.english': 'English',
    'globalConnect.sinhala': 'Sinhala',
    'globalConnect.tamil': 'Tamil',
    'globalConnect.allLevels': 'All Levels',
    'globalConnect.allStatuses': 'All Statuses',
    'globalConnect.now': 'Now',
    'globalConnect.minutesAgo': '{{minutes}} minutes ago',
    'globalConnect.hoursAgo': '{{hours}} hours ago',
    'globalConnect.daysAgo': '{{days}} days ago',
    'globalConnect.private': 'Private',
    'globalConnect.members': 'Members',
    'globalConnect.joinGroupSuccess': 'Successfully joined group',
    'dashboard.recentAchievements': 'Recent Achievements',
    'dashboard.recentLessons': 'Recent Lessons',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.todayProgress': 'Today\'s Progress',
    'dashboard.weeklyGoal': 'Weekly Goal',
    'dashboard.monthlyStats': 'Monthly Statistics',
    'dashboard.learningStreak': 'Learning Streak',
    'dashboard.totalTime': 'Total Time',
    'dashboard.lessonsCompleted': 'Lessons Completed',
    'dashboard.wordsLearned': 'Words Learned',
    'dashboard.accuracy': 'Accuracy',
    'dashboard.speed': 'Speed',
    'dashboard.consistency': 'Consistency',
    'dashboard.motivation': 'Motivation',
    'dashboard.challenges': 'Challenges',
    'dashboard.rewards': 'Rewards',
    'dashboard.badges': 'Badges',
    'dashboard.certificates': 'Certificates',
    'dashboard.leaderboard': 'Leaderboard',
    'dashboard.community': 'Community',
    'dashboard.friends': 'Friends',
    'dashboard.mentors': 'Mentors',
    'dashboard.students': 'Students',
    'dashboard.recommendations': 'Recommendations',
    'dashboard.suggestions': 'Suggestions',
    'dashboard.tips': 'Tips',
    'dashboard.tutorials': 'Tutorials',
    'dashboard.help': 'Help',
    'dashboard.support': 'Support',
    'dashboard.feedback': 'Feedback',
    'dashboard.report': 'Report',
    'dashboard.analytics': 'Analytics',
    'dashboard.insights': 'Insights',
    'dashboard.trends': 'Trends',
    'dashboard.patterns': 'Patterns',
    'dashboard.objectives': 'Objectives',
    'dashboard.milestones': 'Milestones',
    'dashboard.checkpoints': 'Checkpoints',
    'dashboard.assessments': 'Assessments',
    'dashboard.tests': 'Tests',
    'dashboard.quizzes': 'Quizzes',
    'dashboard.exercises': 'Exercises',
    'dashboard.practices': 'Practices',
    'dashboard.sessions': 'Sessions',
    'dashboard.courses': 'Courses',
    'dashboard.modules': 'Modules',
    'dashboard.units': 'Units',
    'dashboard.chapters': 'Chapters',
    'dashboard.topics': 'Topics',
    'dashboard.subjects': 'Subjects',
    'dashboard.categories': 'Categories',
    'dashboard.tags': 'Tags',
    'dashboard.labels': 'Labels',
    'dashboard.filters': 'Filters',
    'dashboard.sort': 'Sort',
    'dashboard.browse': 'Browse',
    'dashboard.explore': 'Explore',
    'dashboard.discover': 'Discover',
    'dashboard.find': 'Find',
    'dashboard.locate': 'Locate',
    'dashboard.navigate': 'Navigate',
    'dashboard.guide': 'Guide',
    'dashboard.direct': 'Direct',
    'dashboard.lead': 'Lead',
    'dashboard.follow': 'Follow',
    'dashboard.track': 'Track',
    'dashboard.monitor': 'Monitor',
    'dashboard.observe': 'Observe',
    'dashboard.watch': 'Watch',
    'dashboard.view': 'View',
    'dashboard.see': 'See',
    'dashboard.look': 'Look',
    'dashboard.eye': 'Eye',
    'dashboard.vision': 'Vision',
    'dashboard.sight': 'Sight',
    'dashboard.perspective': 'Perspective',
    'dashboard.angle': 'Angle',
    'dashboard.aspect': 'Aspect',
    'dashboard.side': 'Side',
    'dashboard.part': 'Part',
    'dashboard.section': 'Section',
    'dashboard.area': 'Area',
    'dashboard.zone': 'Zone',
    'dashboard.region': 'Region',
    'dashboard.territory': 'Territory',
    'dashboard.domain': 'Domain',
    'dashboard.field': 'Field',
    'dashboard.scope': 'Scope',
    'dashboard.range': 'Range',
    'dashboard.span': 'Span',
    'dashboard.extent': 'Extent',
    'dashboard.coverage': 'Coverage',
    'dashboard.reach': 'Reach',
    'dashboard.access': 'Access',
    'dashboard.entry': 'Entry',
    'dashboard.gateway': 'Gateway',
    'dashboard.portal': 'Portal',
    'dashboard.interface': 'Interface',
    'dashboard.surface': 'Surface',
    'dashboard.layer': 'Layer',
    'dashboard.level': 'Level',
    'dashboard.tier': 'Tier',
    'dashboard.grade': 'Grade',
    'dashboard.rank': 'Rank',
    'dashboard.position': 'Position',
    'dashboard.place': 'Place',
    'dashboard.spot': 'Spot',
    'dashboard.point': 'Point',
    'dashboard.location': 'Location',
    'dashboard.coordinates': 'Coordinates',
    'dashboard.address': 'Address',
    'dashboard.destination': 'Destination',
    'dashboard.target': 'Target',
    'dashboard.goal': 'Goal',
    'dashboard.objective': 'Objective',
    'dashboard.aim': 'Aim',
    'dashboard.purpose': 'Purpose',
    'dashboard.intent': 'Intent',
    'dashboard.plan': 'Plan',
    'dashboard.strategy': 'Strategy',
    'dashboard.approach': 'Approach',
    'dashboard.method': 'Method',
    'dashboard.technique': 'Technique',
    'dashboard.tactic': 'Tactic',
    'dashboard.process': 'Process',
    'dashboard.procedure': 'Procedure',
    'dashboard.step': 'Step',
    'dashboard.phase': 'Phase',
    'dashboard.stage': 'Stage',
    'dashboard.period': 'Period',
    'dashboard.interval': 'Interval',
    'dashboard.duration': 'Duration',
    'dashboard.timeframe': 'Timeframe',
    'dashboard.schedule': 'Schedule',
    'dashboard.timeline': 'Timeline',
    'dashboard.calendar': 'Calendar',
    'dashboard.date': 'Date',
    'dashboard.time': 'Time',
    'dashboard.moment': 'Moment',
    'dashboard.instant': 'Instant',
    'dashboard.second': 'Second',
    'dashboard.minute': 'Minute',
    'dashboard.hour': 'Hour',
    'dashboard.day': 'Day',
    'dashboard.week': 'Week',
    'dashboard.month': 'Month',
    'dashboard.year': 'Year',
    'dashboard.decade': 'Decade',
    'dashboard.century': 'Century',
    'dashboard.millennium': 'Millennium',
    'dashboard.era': 'Era',
    'dashboard.age': 'Age',
    'dashboard.generation': 'Generation',
    'dashboard.epoch': 'Epoch',
    'dashboard.cycle': 'Cycle',
    'dashboard.rotation': 'Rotation',
    'dashboard.revolution': 'Revolution',
    'dashboard.evolution': 'Evolution',
    'dashboard.development': 'Development',
    'dashboard.growth': 'Growth',
    'dashboard.progress': 'Progress',
    'dashboard.advancement': 'Advancement',
    'dashboard.improvement': 'Improvement',
    'dashboard.enhancement': 'Enhancement',
    'dashboard.upgrade': 'Upgrade',
    'dashboard.update': 'Update',
    'dashboard.refresh': 'Refresh',
    'dashboard.renewal': 'Renewal',
    'dashboard.restoration': 'Restoration',
    'dashboard.recovery': 'Recovery',
    'dashboard.revival': 'Revival',
    'dashboard.rebirth': 'Rebirth',
    'dashboard.renaissance': 'Renaissance',
    'lessons.title': 'Lessons & Practice',
    'lessons.subtitle': 'Learn new languages with personalized lessons',
    'lessons.progress': 'Progress',
    'lessons.completed': 'Completed',
    'lessons.groupWelcome': 'Welcome to the Learning Group!',
    'lessons.groupWelcomeDesc': 'Start learning with your group',
    'lessons.letterLearning': 'Letter Learning',
    'lessons.totalLessons': 'Total Lessons',
    'lessons.averageProgress': 'Average Progress',
    'lessons.totalMinutes': 'Total Minutes',
    'lessons.searchPlaceholder': 'Search lessons...',
    'lessons.review': 'Review',
    'lessons.continue': 'Continue',
    'lessons.start': 'Start',
    'lessons.noLessonsFound': 'No lessons found',
    'lessons.tryDifferentFilters': 'Try different filters',
    'lessons.clearFilters': 'Clear filters',
    'globalConnect.title': 'Global Connect',
    'globalConnect.findUsers': 'Find Users',
    'forums.title': 'Forums & Articles',
    'forums.subtitle': 'Share ideas and learn with a global community',
    'forums.categories': 'Categories',
    'forums.stats.activeUsers': 'Active Users',
    'forums.searchPosts': 'Search posts...',
    'forums.moreFilters': 'More Filters',
    'forums.noPostsFound': 'No posts found',
    'forums.tryDifferentFilters': 'Try different filters',
    'forums.createPost': 'Create New Post',
    'forums.allCategories': 'All Categories',
    'forums.general': 'General',
    'forums.learning': 'Learning',
    'forums.questions': 'Questions',
    'forums.tips': 'Tips',
    'forums.offTopic': 'Off Topic',
    'forums.stats.totalPosts': 'Total Posts',
    'forums.stats.totalReplies': 'Total Replies',
    'forums.stats.totalViews': 'Total Views',
    'forums.selectCategory': 'Select Category',
    'forums.selectLanguage': 'Select Language',
    'profile.title': 'Profile',
    'profile.settings': 'Settings',
    'profile.statistics': 'Statistics',
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'settings.notifications': 'Notifications',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'auth.loginSuccess': 'Login successful!',
    'auth.loginError': 'Login error',
    'auth.registerSuccess': 'Registration successful!',
    'auth.registerError': 'Registration error',
    'auth.emailRequired': 'Email is required',
    'auth.emailInvalid': 'Invalid email',
    'auth.emailPlaceholder': 'Enter your email',
    'auth.passwordRequired': 'Password is required',
    'auth.passwordMinLength': 'Password must be at least 6 characters',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.nameRequired': 'Name is required',
    'auth.nameMinLength': 'Name must be at least 2 characters',
    'auth.namePlaceholder': 'Enter your full name',
    'auth.nativeLanguageRequired': 'Native language is required',
    'auth.nativeLanguage': 'Native Language',
    'auth.selectNativeLanguage': 'Select native language',
    'auth.learningLanguages': 'Learning Languages',
    'auth.selectAtLeastOneLanguage': 'Select at least one language',
    'auth.passwordHelper': 'At least 8 characters, uppercase, lowercase and number',
    'auth.passwordPattern': 'Password must contain uppercase, lowercase and number',
    'auth.confirmPasswordRequired': 'Confirm password is required',
    'auth.confirmPassword': 'Confirm Password',
    'auth.confirmPasswordPlaceholder': 'Enter password again',
    'auth.passwordsDoNotMatch': 'Passwords do not match',
    'auth.orContinueWith': 'Or continue with',
    'auth.noAccount': "Don't have an account?",
    'auth.haveAccount': 'Already have an account?',
    'auth.resetEmailSent': 'Password reset email sent',
    'auth.resetError': 'Error sending reset email',
    'auth.checkYourEmail': 'Check your email',
    'auth.resetEmailInstructions': 'We sent you instructions to reset your password',
    'auth.sendAnotherEmail': 'Send another email',
    'auth.backToLogin': 'Back to login',
    'auth.forgotPasswordInstructions': 'Enter your email and we will send you instructions to reset your password',
    'auth.sendResetEmail': 'Send reset email',
  },
  si: {
    'app.title': 'LanguageConnect',
    'app.subtitle': 'භාෂා සහ සංස්කෘති සම්බන්ධ කිරීම',
    'auth.login': 'පුරන්න',
    'auth.register': 'ලියාපදිංචි වන්න',
    'auth.email': 'විද්‍යුත් තැපෑල',
    'auth.password': 'මුරපදය',
    'auth.name': 'සම්පූර්ණ නම',
    'auth.forgotPassword': 'මුරපදය අමතකයි',
    'auth.signInWithGoogle': 'Google සමඟ පුරන්න',
    'auth.signInWithFacebook': 'Facebook සමඟ පුරන්න',
    'dashboard.welcome': 'ආයුබෝවන්',
    'dashboard.lessons': 'පාඩම් සහ පුහුණුව',
    'dashboard.chat': 'කතාබහ සහ කණ්ඩායම්',
    'dashboard.forums': 'සංසද සහ ලිපි',
    'dashboard.profile': 'පැතිකඩ',
    'lessons.title': 'පාඩම් සහ පුහුණුව',
    'lessons.progress': 'ප්‍රගතිය',
    'lessons.completed': 'සම්පූර්ණ',
    'globalConnect.title': 'Global Connect',
    'globalConnect.findUsers': 'පරිශීලකයන් සොයන්න',
    'globalConnect.startChat': 'කතාබහ ආරම්භ කරන්න',
    'forums.title': 'සංසද සහ ලිපි',
    'forums.categories': 'වර්ග',
    'profile.title': 'පැතිකඩ',
    'profile.settings': 'සැකසුම්',
    'profile.statistics': 'සංඛ්‍යාලේඛන',
    'settings.title': 'සැකසුම්',
    'settings.language': 'භාෂාව',
    'settings.theme': 'තේමාව',
    'settings.notifications': 'දැනුම්දීම්',
    'common.loading': 'පූරණය වෙමින්...',
    'common.error': 'දෝෂය',
    'common.success': 'සාර්ථක',
    'common.save': 'සුරකින්න',
    'common.cancel': 'අවලංගු කරන්න',
    'common.delete': 'මකන්න',
    'common.edit': 'සංස්කරණය',
    'common.close': 'වසන්න',
  },
  ta: {
    'app.title': 'LanguageConnect',
    'app.subtitle': 'மொழிகள் மற்றும் கலாச்சாரங்களை இணைத்தல்',
    'auth.login': 'உள்நுழைய',
    'auth.register': 'பதிவு செய்',
    'auth.email': 'மின்னஞ்சல்',
    'auth.password': 'கடவுச்சொல்',
    'auth.name': 'முழு பெயர்',
    'auth.forgotPassword': 'கடவுச்சொல் மறந்துவிட்டது',
    'auth.signInWithGoogle': 'Google உடன் உள்நுழைய',
    'auth.signInWithFacebook': 'Facebook உடன் உள்நுழைய',
    'dashboard.welcome': 'வரவேற்கிறோம்',
    'dashboard.lessons': 'பாடங்கள் மற்றும் பயிற்சி',
    'dashboard.chat': 'அரட்டை மற்றும் குழுக்கள்',
    'dashboard.forums': 'மன்றங்கள் மற்றும் கட்டுரைகள்',
    'dashboard.profile': 'சுயவிவரம்',
    'lessons.title': 'பாடங்கள் மற்றும் பயிற்சி',
    'lessons.progress': 'முன்னேற்றம்',
    'lessons.completed': 'முடிந்தது',
    'globalConnect.title': 'Global Connect',
    'globalConnect.findUsers': 'பயனர்களைக் கண்டறியவும்',
    'globalConnect.startChat': 'அரட்டையைத் தொடங்கவும்',
    'forums.title': 'மன்றங்கள் மற்றும் கட்டுரைகள்',
    'forums.categories': 'வகைகள்',
    'profile.title': 'சுயவிவரம்',
    'profile.settings': 'அமைப்புகள்',
    'profile.statistics': 'புள்ளிவிவரங்கள்',
    'settings.title': 'அமைப்புகள்',
    'settings.language': 'மொழி',
    'settings.theme': 'தீம்',
    'settings.notifications': 'அறிவிப்புகள்',
    'common.loading': 'ஏற்றுகிறது...',
    'common.error': 'பிழை',
    'common.success': 'வெற்றி',
    'common.save': 'சேமி',
    'common.cancel': 'ரத்து செய்',
    'common.delete': 'நீக்கு',
    'common.edit': 'திருத்து',
    'common.close': 'மூடு',
  },
}

// Auth Provider
function AuthProvider({ children }: { children: ReactNode }) {
  const [user, setUser] = useState<AuthUser | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    checkAuth()
  }, [])

  const checkAuth = async () => {
    try {
      // Check localStorage for saved user (only on client side)
      if (typeof window !== 'undefined') {
        const savedUser = localStorage.getItem('auth-user')
        if (savedUser) {
          setUser(JSON.parse(savedUser))
        }
      }
    } catch (error) {
      console.error('Auth check failed:', error)
    } finally {
      setLoading(false)
    }
  }

  const signIn = async (email: string, password: string): Promise<boolean> => {
    try {
      // Check for admin user
      if (email === 'admin@languageconnect.com' && password === 'admin123') {
        const adminUser = {
          _id: 'admin_user',
          email: 'admin@languageconnect.com',
          name: 'מנהל המערכת',
          avatar: undefined,
          nativeLanguage: 'he',
          learningLanguages: ['en', 'ar', 'es', 'fr'],
          currentLevel: 'advanced',
          totalPoints: 1000,
          streak: 30,
          role: 'admin'
        }
        
        setUser(adminUser)
        if (typeof window !== 'undefined') {
          localStorage.setItem('auth-user', JSON.stringify(adminUser))
        }
        return true
      }
      
      // For demo purposes, create a demo user
      const demoUser = {
        _id: 'demo_user_' + Date.now(),
        email: email,
        name: 'Demo User',
        avatar: undefined,
        nativeLanguage: 'he',
        learningLanguages: ['en', 'ar'],
        currentLevel: 'beginner',
        totalPoints: 0,
        streak: 0,
        role: 'user'
      }
      
      setUser(demoUser)
      if (typeof window !== 'undefined') {
        localStorage.setItem('auth-user', JSON.stringify(demoUser))
      }
      return true
    } catch (error) {
      console.error('Login failed:', error)
      return false
    }
  }

  const signUp = async (formData: {
    email: string
    password: string
    name: string
    nativeLanguage: string
    learningLanguages: string[]
  }): Promise<boolean> => {
    try {
      // For demo purposes, create a demo user
      const demoUser = {
        _id: 'demo_user_' + Date.now(),
        email: formData.email,
        name: formData.name,
        avatar: undefined,
        nativeLanguage: formData.nativeLanguage,
        learningLanguages: formData.learningLanguages,
        currentLevel: 'beginner',
        totalPoints: 0,
        streak: 0
      }
      
      setUser(demoUser)
      if (typeof window !== 'undefined') {
        localStorage.setItem('auth-user', JSON.stringify(demoUser))
      }
      return true
    } catch (error) {
      console.error('Registration failed:', error)
      return false
    }
  }

  const signOut = async () => {
    try {
      if (typeof window !== 'undefined') {
        localStorage.removeItem('auth-user')
      }
      setUser(null)
    } catch (error) {
      console.error('Logout failed:', error)
    }
  }

  const signInWithGoogle = async (): Promise<boolean> => {
    try {
      // For now, create a demo user for Google sign in
      const demoUser = {
        _id: 'google_demo_user',
        email: 'demo@google.com',
        name: 'Google Demo User',
        avatar: undefined,
        nativeLanguage: 'he',
        learningLanguages: ['en', 'ar'],
        currentLevel: 'beginner',
        totalPoints: 0,
        streak: 0
      }
      
      setUser(demoUser)
      if (typeof window !== 'undefined') {
        localStorage.setItem('auth-user', JSON.stringify(demoUser))
      }
      return true
    } catch (error) {
      console.error('Google sign in failed:', error)
      return false
    }
  }

  const signInWithFacebook = async (): Promise<boolean> => {
    try {
      // For now, create a demo user for Facebook sign in
      const demoUser = {
        _id: 'facebook_demo_user',
        email: 'demo@facebook.com',
        name: 'Facebook Demo User',
        avatar: undefined,
        nativeLanguage: 'he',
        learningLanguages: ['en', 'ar'],
        currentLevel: 'beginner',
        totalPoints: 0,
        streak: 0
      }
      
      setUser(demoUser)
      if (typeof window !== 'undefined') {
        localStorage.setItem('auth-user', JSON.stringify(demoUser))
      }
      return true
    } catch (error) {
      console.error('Facebook sign in failed:', error)
      return false
    }
  }

  const resetPassword = async (email: string): Promise<boolean> => {
    try {
      // For demo purposes, always return success
      return true
    } catch (error) {
      console.error('Reset password failed:', error)
      return false
    }
  }

  const value = {
    user,
    loading,
    signIn,
    signUp,
    signOut,
    signInWithGoogle,
    signInWithFacebook,
    resetPassword,
  }

  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>
}

// Language Provider
function LanguageProvider({ children }: { children: ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState('he')

  const isRTL = currentLanguage === 'he' || currentLanguage === 'ar'

  const t = (key: string, params?: Record<string, string | number>) => {
    const translation = (translations[currentLanguage as keyof typeof translations] as Record<string, string>)?.[key] || key
    
    if (params) {
      return Object.entries(params).reduce(
        (str, [paramKey, paramValue]) => str.replace(`{{${paramKey}}}`, String(paramValue)),
        translation
      )
    }
    
    return translation
  }

  const value = {
    currentLanguage,
    setLanguage: setCurrentLanguage,
    isRTL,
    t,
  }

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

// Theme Provider
function ThemeProviderWrapper({ children }: { children: ReactNode }) {
  return <ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>{children}</ThemeProvider>
}

// Query Client
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 5 * 60 * 1000, // 5 minutes
      cacheTime: 10 * 60 * 1000, // 10 minutes
    },
  },
})

// Main Providers Component
export function Providers({ children }: { children: ReactNode }) {
  return (
    <QueryClientProvider client={queryClient}>
      <ThemeProviderWrapper>
        <LanguageProvider>
          <AuthProvider>
            <SocketProvider>
              {children}
            </SocketProvider>
          </AuthProvider>
        </LanguageProvider>
      </ThemeProviderWrapper>
    </QueryClientProvider>
  )
}
